### ISSUE TITLE
monitor action of zerodb on top of ssd fails after node reboot

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#108]
I've a zerodb that has been created to provide namespace for the vdisk of a VM.
After a rebooted the node, I get this error on the robot:
```
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/zerodb/zerodb.py", line 51, in _monitor
    self._node_sal.zerodbs.mount_subvolume(self.name, self.data['path'])
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/zerodb/__init__.py", line 162, in mount_subvolume
    raise RuntimeError('Failed to find filesystem for zerodb {}'.format(zdb_name))
RuntimeError: Failed to find filesystem for zerodb zdb_local_zdb_newls
```
Seems there is something wrong when the zerodb service try to restart the zerodb.

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscale_lib/commit/617afe7e8c1be59501f8c940b3375abc3cbe1072

**Comment by serboctor** [comment]
Note to QA: the fix is in jumpscale_lib, which means that for existing nodes you need to terminate the 0-robot container so it would be recreated with the updated code.
The easiest way to test this fix is to create a zerodb service(obviously with `diskType` = ssd) on a node, and after it has been installed, reboot the node. At first the monitoring action of the zerodb will fail because it is waiting for the node monitor to be done and to mount the disks. This IS normal. And then the monitor of the zerodb will work normally and the container will be recreated and the process will start normally.

**Comment by Pishoy** [comment]
verified 
---- before reboot 
```
args = {
    'size': 5,
    'password': 'password',
    'diskType': 'ssd'
}
namespace = robot.services.create('github.com/threefoldtech/0-templates/namespace/0.0.1', 'namespace_two', data=args)
namespace.schedule_action('install').wait(die='true') ;
## wait till zdb namespace container created 
namespace = robot.services.get(name='namespace_two')

In [49]: namespace.data
Out[49]: 
{'data': {'diskType': 'ssd',
  'mode': 'user',
  'nsName': 'id3nt0eyts',
  'password': 'password',
  'public': False,
  'size': 5,
  'zerodb': 'lojs7'},
 'guid': 'b0b91038-df10-4955-8d07-7ae3fc879391',
 'name': 'namespace_two',
 'public': False,
 'state': [{'category': 'actions', 'state': 'ok', 'tag': 'install'},
  {'category': 'status', 'state': 'ok', 'tag': 'running'}],
 'template': 'github.com/threefoldtech/0-templates/namespace/0.0.1',
 'version': '0.0.1'}

In [50]: node_client.client.bash('df -kh /mnt/zdbs/lojs7').get()
Out[50]: 
STATE: 0 SUCCESS
STDOUT:
Filesystem                Size      Used Available Use% Mounted on
/dev/sdb1                59.6G     16.5M     58.6G   0% /mnt/zdbs/lojs7

STDERR:

DATA:
In [54]: node_client.healthcheck.node.reboot()

---- after reboot 
```
In [57]: node_client.client.container.list()

In [67]: namespace = robot.services.get(name='namespace_two')

In [68]: namespace.data
Out[68]: 
{'data': {'diskType': 'ssd',
  'mode': 'user',
  'nsName': 'id3nt0eyts',
  'password': 'password',
  'public': False,
  'size': 5,
  'zerodb': 'lojs7'},
 'guid': 'b0b91038-df10-4955-8d07-7ae3fc879391',
 'name': 'namespace_two',
 'public': False,
 'state': [{'category': 'actions', 'state': 'ok', 'tag': 'install'}],
 'template': 'github.com/threefoldtech/0-templates/namespace/0.0.1',
 'version': '0.0.1'}
In [70]: node_client.containers.list()
Out[70]: 
[Container <lojs7>,
 Container <zrobot>]
```
above error does not exist on log after reboot
