### ISSUE TITLE
install s3 raises an error while creating the namespace

### ISSUE THREAD

**Issue by islamTaha12** [threefoldtech/0-templates#114]
```
[Tue18 13:15] - base.py           :214 :service-665ea8a0-edfe-4907-913a-f775a0bd15c0 - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 101, in install
    namespace, node_index = self._create_namespace(node_index, storage_key, self.data['nsPassword'])
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 241, in _create_namespace
    namespace = install_namespace(robot, self.guid, self.data['storageType'], self.data['storageSize'], password)
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 267, in install_namespace
    raise RuntimeError(task.eco.message)
RuntimeError: unsupported operand type(s) for +=: 'int' and 'str'
```

**env**
js: dev
0-robot: dev
0-template: dev

**Comment by zaibon** [comment]
@islamTaha12 can you check the revision of the 0-template repo on that node that returned that error ?
