### ISSUE TITLE
Error in creation of zerodb namespace during s3 deployement

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#121]
It seems that sometimes, the logic that decide where to put the zerodb creates some kind of conflict

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 344, in install_namespace
    raise NamespaceDeployError(str(err), node)
s3.NamespaceDeployError: (NamespaceDeployError(...), "(NamespaceDeployError(...), 'failed to mount partition: mount: mounting /dev/sdo1 on /mnt/storagepools/sdo failed: Device or resource busy\\n')")
2018-09-21T13:12:44Z <Greenlet "Greenlet-1" at 0x7f49c1acfe48: install_namespace(name='ca78f289-7a4e-43b2-a1d0-ba13f3fe6b5c', disk_type='hdd', password='7hcpwpsja7fivyv1axidd0j9e1pp0iz6', node={'robot_address': 'http://10.147.20.55:6600', 'far, size=2000)> failed with NamespaceDeployError

Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 340, in install_namespace
    raise NamespaceDeployError(task.eco.message, node)
s3.NamespaceDeployError: (NamespaceDeployError(...), 'failed to mount partition: mount: mounting /dev/sdp1 on /mnt/storagepools/sdp failed: Device or resource busy\n')
```

**Comment by serboctor** [comment]
I can't reproduce this at all, neither locally nor on tlre. Calling `disk.mount` on the a device and a mountpoint that's already been mounted produces this error. However, in both places where we call `disk.mount`, we check first if this mountpoint is in the node mounts so I don't understand how this could happen except if the `info.disk` suddenly returns incorrect info.

**Comment by zaibon** [comment]
yep I don't get it either. I'll lower the priority since I never hit that problem anymore so far. Let's see if that pop up again when we'll do tests at scale

**Comment by serboctor** [comment]
Sounds good, may be next time we try to keep the node and investigate on it before resetting.

**Comment by zaibon** [comment]
After a week of more testing, this bug has not showed up anymore. closing

**Comment by zaibon** [comment]
we've encountered the bug again, re-opening

**Comment by zaibon** [comment]
since https://github.com/threefoldtech/0-templates/pull/159 we didn't see this error anymore.
