### ISSUE TITLE
Deploying a vm is raising a port forward error if the name is exisiting

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#136]
**Description**
I tried to deploy 2 s3, the first one installed correctly but the second one raised the following error

**0-robot log**
```python
[Mon01 17:12] - pywsgi.py         :1182:j.zerorobot          - INFO     - ::1 - - [2018-10-01 17:12:59] "GET /services/baf56663-7d01-48de-a4f5-9db3afec0356/task_list/2ae144a6-fc72-4248-980c-30f0794f8e34 HTTP/1.1" 200 363 0.002126
[Mon01 17:12] - base.py           :214 :service-11054ea5-cc62-43f1-9dc6-2f54580499da - ERROR    - error executing action add_portforward:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 76, in execute
    self._result = self._func(**self._args)
  File "/opt/code/github/threefoldtech/0-templates/templates/dm_vm/dm_vm.py", line 228, in add_portforward
    result = self._node_vm.schedule_action('add_portforward', args=forward).wait(die=True).result
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 131, in wait
    raise RuntimeError(self.eco.message)
RuntimeError: port forward with name minio already exist
```

**js_logs**
```python
In [8]: demo.deploy_n(1,'tlre', 20000, 16, 4)
[Mon01 17:12] - s3.py             :138 :j.s3demo             - INFO     - install zerotier client
[Mon01 17:12] - s3.py             :141 :j.s3demo             - INFO     - install s3 service
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/opt/code/github/threefoldtech/demo/demo.py in <module>()
----> 1 demo.deploy_n(1,'tlre', 20000, 16, 4)

/opt/code/github/threefoldtech/demo/demo.py in deploy_n(self, n, farm, size, data, parity, login, password)
     24             name = 's3_demo_%d' % i
     25             self.s3[name] = S3Manager(self, name)
---> 26             self.s3[name].deploy(farm, size=size, data=data, parity=parity, login=login, password=password)
     27 
     28     def urls(self):

/opt/code/github/threefoldtech/demo/s3.py in deploy(self, farm, size, data, parity, login, password)
    150             'minioPassword': password}
    151         self._service = self.dm_robot.services.find_or_create('s3', self.name, data=s3_data)
--> 152         return self._service.schedule_action('install').wait(die=True)
    153 
    154     @property

/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise RuntimeError(self.eco.message)
    132 
    133         return self

RuntimeError: port forward with name minio already exist
```

**Repos**
0-robot dev
js dev

**Comment by serboctor** [comment]
https://github.com/threefoldtech/0-templates/commit/6196fe11541ef8d0397db4e0f511a14fb24fa873
https://github.com/threefoldtech/0-templates/commit/9d1ec927c8cd81df8ab343238b840b1067d0ef6f

**Comment by serboctor** [comment]
Modified the `add_portforward ` action to only raise the name error if either the target or source port are different from the existing one.

**Comment by Pishoy** [comment]
verified 

```
In [46]: data = {
    ...:     'nodeId': 'ac1f6b4575a8',
    ...:     'disks': [{
    ...:         'diskType': 'hdd',
    ...:         'size': 5,
    ...:         'mountPoint': '/mnt',
    ...:         'filesystem': 'btrfs',
    ...:         'label': 'test',
    ...:     }],
    ...:     'mgmtNic': {'id':'1c33c1ced064fefe', 'ztClient': 'ztclient', 'type': 'zerotier'},
    ...:     'image': 'ubuntu',
    ...:     'ports': [{'name': 'ssh', 'source': 2222, 'target': 22}, {'name': 'ssh', 'source': 2233, 'target': 22}],
    ...:     'configs': [{'path': '/root/.ssh/authorized_keys', 'content': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8o0jEGYqe2k7J0TNL6Gg8h86ic3ReiC6THlBnOKPDiKProj/4uMTmi1Qf5OcLIdeHgcP+zy+ZL4kpP7N6VTALRPiT
    ...: n6Lty6ZP+5mQocaJYosoGLzB6+lx1NW/zXtscv4V3goULiDEx9SBzSuD8wS0k00iHcRjmuFUIfERyYR8mjmWC/sRf1Y7qk9kQjFOLW5Sw0+RLrxr4l2ur/n8bDVgGVpzWypKIsqRU6Rf1HdXWmdAMCucPAkxR5WNies5QFOkyllxI6Fq+G9M0Uf+EubpfpC1oOM
    ...: WjNFy781M4KZF+FXODcBlwevfvk0HH/5mTHOymIfwVV8vjRzycxjuQib3 pishoy@Bishoy-laptop', 'name': 'sshkey'}]
    ...: }

In [47]: robot.services.names
Out[47]: 
{'main': robot://local/github.com/threefoldtech/0-templates/zerotier_client/0.0.1?name=main&guid=5e96aa8d-5f42-477d-8299-18334ea12d33,
 'portforward': robot://local/github.com/threefoldtech/0-templates/dm_vm/0.0.1?name=portforward&guid=2405713f-c6d4-4668-8d1d-3fbbd105868d}

In [48]: for i in [ 'portforward' ] : service = robot.services.get(name=i) ;  service.schedule_action('uninstall').wait(die=True) ; service.delete()

In [49]: vm = robot.services.create('github.com/threefoldtech/0-templates/dm_vm/0.0.1','vmtotestportforward', data)

In [50]: vm.schedule_action('install').wait(die=True)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/bin/js_shell in <module>()
----> 1 vm.schedule_action('install').wait(die=True)

/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise RuntimeError(self.eco.message)
    132 
    133         return self

RuntimeError: Element with name ssh already exists

In [82]: data = {
    ...:     'nodeId': 'ac1f6b4575a8',
    ...:     'disks': [{
    ...:         'diskType': 'hdd',
    ...:         'size': 5,
    ...:         'mountPoint': '/mnt',
    ...:         'filesystem': 'btrfs',
    ...:         'label': 'test',
    ...:     }],
    ...:     'mgmtNic': {'id':'1c33c1ced064fefe', 'ztClient': 'ztclient', 'type': 'zerotier'},
    ...:     'image': 'ubuntu',
    ...:     'ports': [{'name': 'ssh', 'source': 1111, 'target': 22}, {'name': 'ssh1', 'source': 1113, 'target': 22}],
    ...:     'configs': [{'path': '/root/.ssh/authorized_keys', 'content': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8o0jEGYqe2k7J0TNL6Gg8h86ic3ReiC6THlBnOKPDiKProj/4uMTmi1Qf5OcLIdeHgcP+zy+ZL4kpP7N6VTALRPiT
    ...: n6Lty6ZP+5mQocaJYosoGLzB6+lx1NW/zXtscv4V3goULiDEx9SBzSuD8wS0k00iHcRjmuFUIfERyYR8mjmWC/sRf1Y7qk9kQjFOLW5Sw0+RLrxr4l2ur/n8bDVgGVpzWypKIsqRU6Rf1HdXWmdAMCucPAkxR5WNies5QFOkyllxI6Fq+G9M0Uf+EubpfpC1oOM
    ...: WjNFy781M4KZF+FXODcBlwevfvk0HH/5mTHOymIfwVV8vjRzycxjuQib3 pishoy@Bishoy-laptop', 'name': 'sshkey'}]
    ...: }

In [83]: vm = robot.services.create('github.com/threefoldtech/0-templates/dm_vm/0.0.1','vmtotestportforward5', data)

In [84]: vm.schedule_action('install').wait(die=True)
Out[84]: install
- from my laptop to ZOS node which contain the vm 
pishoy@pishoy-laptop:~$ ssh root@10.102.234.229 -p1111
Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.4.0-21-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Mon Oct 15 12:38:59 2018 from 10.102.37.79
root@ubuntu:~# 

```
- js version 
```
jumpscale_core
commit 81301a84ddf956f36cfdedc0466fcac091ca6271
Merge: e01242b 951990e
Author: Ahmed T. Youssef <xmonader@gmail.com>
Date:   Wed Oct 10 09:52:28 2018 +0200

    Merge pull request #139 from threefoldtech/nacl_socket
    
    Nacl socket
jumpscale_lib
commit e8ba33e68e5448896122042aceedc6624bbfd259
Author: BolaNasr <bola.e.nasr@gmail.com>
Date:   Sun Oct 14 15:53:58 2018 +0200

    gateway, Zdb and any container created join automatically public threefold grid #184
jumpscale_prefab
commit 44e92d0c9e47f663c1ede06e8d8c983905da581d
Author: Abdelrahman Hussein <ahussein.abdelrahman@gmail.com>
Date:   Sun Sep 9 15:08:07 2018 +0200

    update installtion of atomicswap prefab
root@e7605ba47d5c:/opt/code/github/threefoldte
0-templates
commit 90b252f65f6ff70671ec191b28953df19f8943ab
Author: Christophe de Carvalho Pereira Martins <christophe.dcpm@gmail.com>
Date:   Fri Oct 12 12:07:19 2018 +0200

```
