### ISSUE TITLE
unauthorised access error while deploying s3

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#137]
**Important Hint**
This is a sneaky error, sometimes s3 throwes it and others s3 is installed well.

**Description**
- while deploying an s3 instance, sometimes It throws this error.

**re-produce**
using the demo.py tool
```python
demo.deploy_n(1, 'tlre', size=20000, data=16, parity=4, login='admin',password='adminadmin')```
s3 = demo.s3['s3_demo_3']
print(s3.service.logs)

**Output**
```python
In [44]: print(s3.service.logs)
2018-10-02 12:12:09,557 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:181 - INFO - wait for all namespaces and vm to be installed
2018-10-02 12:12:09,558 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:311 - INFO - create namespaces to be used as a backend for minio
2018-10-02 12:12:09,558 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:313 - INFO - compute how much zerodb are required
2018-10-02 12:12:09,558 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:326 - INFO - namespaces required: 25 of 1000GB
2018-10-02 12:12:09,559 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:327 - INFO - namespaces already deployed 0
2018-10-02 12:12:09,563 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:351 - INFO - create namespaces to be used as a tlog for minio
2018-10-02 12:12:09,566 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:382 - INFO - create the zero-os vm on which we will create the minio container
2018-10-02 12:12:13,805 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:440 - INFO - number of possible nodes to use for namespace deployments 23
2018-10-02 12:12:13,805 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01_tlog on node ac1f6b457ae0
2018-10-02 12:12:13,806 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:440 - INFO - number of possible nodes to use for namespace deployments 23
2018-10-02 12:12:13,806 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47a6cc
2018-10-02 12:12:13,807 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47ad0c
2018-10-02 12:12:13,807 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47a830
2018-10-02 12:12:13,807 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47acf0
2018-10-02 12:12:13,807 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b479d6c
2018-10-02 12:12:13,808 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b479d58
2018-10-02 12:12:13,808 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47a76c
2018-10-02 12:12:13,808 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47aa18
2018-10-02 12:12:13,809 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b457c84
2018-10-02 12:12:13,809 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b479db4
2018-10-02 12:12:13,809 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47a760
2018-10-02 12:12:13,809 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47aab0
2018-10-02 12:12:13,810 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47aa94
2018-10-02 12:12:13,810 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b457cf0
2018-10-02 12:12:13,810 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b457c58
2018-10-02 12:12:13,810 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b457c30
2018-10-02 12:12:13,811 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47acf8
2018-10-02 12:12:13,811 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b479c14
2018-10-02 12:12:13,811 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47acfc
2018-10-02 12:12:13,812 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47ab18
2018-10-02 12:12:13,812 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47a274
2018-10-02 12:12:13,812 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b457ae0
2018-10-02 12:12:13,812 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b457b3c
2018-10-02 12:12:13,813 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47a6cc
2018-10-02 12:12:13,813 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47ad0c
2018-10-02 12:12:18,789 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:455 - ERROR - we could not deploy on node ac1f6b47ad0c, remove it from the possible node to use
2018-10-02 12:12:18,792 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:455 - ERROR - we could not deploy on node ac1f6b47ad0c, remove it from the possible node to use
2018-10-02 12:12:21,490 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:376 - INFO - tlog namespaces deployed
2018-10-02 12:12:25,176 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:455 - ERROR - we could not deploy on node ac1f6b47ad0c, remove it from the possible node to use
2018-10-02 12:12:50,686 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 1 namespaces deployed, remaining 24
2018-10-02 12:12:51,540 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 2 namespaces deployed, remaining 23
2018-10-02 12:12:52,406 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 3 namespaces deployed, remaining 22
2018-10-02 12:12:52,415 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 4 namespaces deployed, remaining 21
2018-10-02 12:12:52,526 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 5 namespaces deployed, remaining 20
2018-10-02 12:12:52,550 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 6 namespaces deployed, remaining 19
2018-10-02 12:12:53,831 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 7 namespaces deployed, remaining 18
2018-10-02 12:12:53,918 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 8 namespaces deployed, remaining 17
2018-10-02 12:12:53,962 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 9 namespaces deployed, remaining 16
2018-10-02 12:12:54,454 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 10 namespaces deployed, remaining 15
2018-10-02 12:12:55,398 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 11 namespaces deployed, remaining 14
2018-10-02 12:13:02,450 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 12 namespaces deployed, remaining 13
2018-10-02 12:13:02,982 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 13 namespaces deployed, remaining 12
2018-10-02 12:13:04,298 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 14 namespaces deployed, remaining 11
2018-10-02 12:13:05,910 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 15 namespaces deployed, remaining 10
2018-10-02 12:13:07,134 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 16 namespaces deployed, remaining 9
2018-10-02 12:13:08,690 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 17 namespaces deployed, remaining 8
2018-10-02 12:13:09,618 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 18 namespaces deployed, remaining 7
2018-10-02 12:13:09,638 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 19 namespaces deployed, remaining 6
2018-10-02 12:13:36,004 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:455 - ERROR - we could not deploy on node ac1f6b47aa94, remove it from the possible node to use
2018-10-02 12:13:58,190 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 20 namespaces deployed, remaining 5
2018-10-02 12:14:01,754 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 21 namespaces deployed, remaining 4
2018-10-02 12:14:01,775 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:440 - INFO - number of possible nodes to use for namespace deployments 19
2018-10-02 12:14:01,776 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47a830
2018-10-02 12:14:01,776 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b47acf0
2018-10-02 12:14:01,776 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b479d6c
2018-10-02 12:14:01,777 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace 9d5b7389-c943-4c03-959d-69ef4979ea01 on node ac1f6b479d58
2018-10-02 12:14:38,586 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 22 namespaces deployed, remaining 3
2018-10-02 12:14:41,698 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 23 namespaces deployed, remaining 2
2018-10-02 12:14:43,178 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 24 namespaces deployed, remaining 1
2018-10-02 12:14:48,354 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:342 - INFO - 25 namespaces deployed, remaining 0
2018-10-02 12:14:49,247 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:197 - INFO - create the minio service on the vm
2018-10-02 12:14:49,247 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:213 - INFO - wait up to 20 mins for zerorobot until it downloads the repos and starts accepting requests
2018-10-02 12:14:49,253 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:221 - INFO - vm not up yet...waiting some more
2018-10-02 12:14:59,258 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:221 - INFO - vm not up yet...waiting some more
2018-10-02 12:15:09,263 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:221 - INFO - vm not up yet...waiting some more
2018-10-02 12:15:19,268 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:221 - INFO - vm not up yet...waiting some more
2018-10-02 12:15:34,488 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:227 - INFO - install minio
2018-10-02 12:15:34,515 - /opt/code/github/threefoldtech/0-robot/zerorobot/template/base.py:214 - ERROR - error executing action install:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 228, in install
    minio.schedule_action('install').wait(die=True)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/service_proxy.py", line 100, in schedule_action
    raise err
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/service_proxy.py", line 96, in schedule_action
    task, _ = self._zrobot_client.api.services.AddTaskToList(req, service_guid=self.guid)
  File "/opt/code/github/threefoldtech/0-robot/JumpscaleZrobot/clients/zerorobot/client/services_service.py", line 127, in AddTaskToList
    resp = self.client.post(uri, data, headers, query_params, content_type)
  File "/opt/code/github/threefoldtech/0-robot/JumpscaleZrobot/clients/zerorobot/client/http_client.py", line 62, in post
    return self._handle_data(uri, data, headers, params, content_type, self.session.post)
  File "/opt/code/github/threefoldtech/0-robot/JumpscaleZrobot/clients/zerorobot/client/http_client.py", line 58, in _handle_data
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: http://172.29.253.124:6600/services/f5b27f36-8be2-4b4d-90ed-504604c42bab/task_list
```

**Env**
dev
farm: tlre

**Comment by zaibon** [comment]
fixed by: https://github.com/threefoldtech/0-robot/commit/d9615b9bebffa6eb8567fe388d3abdcf714242fb
