### ISSUE TITLE
capacity.threefoldtoken.com connection error while installing s3

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#138]
**Important Hint**
This is a sneaky error, sometimes s3 throwes it and others s3 is installed well.

**Description**
- while deploying an s3 instance, sometimes It throws this error.

**re-produce**
using the demo.py tool
```python
demo.deploy_n(1, 'tlre', size=20000, data=16, parity=4, login='admin',password='adminadmin')```
s3 = demo.s3['s3_demo_3']
print(s3.service.logs)

```python
In [37]: print(s3_3.service.logs)
2018-10-02 11:11:12,773 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:181 - INFO - wait for all namespaces and vm to be installed
2018-10-02 11:11:12,773 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:311 - INFO - create namespaces to be used as a backend for minio
2018-10-02 11:11:12,774 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:313 - INFO - compute how much zerodb are required
2018-10-02 11:11:12,774 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:326 - INFO - namespaces required: 25 of 1000GB
2018-10-02 11:11:12,774 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:327 - INFO - namespaces already deployed 0
2018-10-02 11:11:12,778 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:351 - INFO - create namespaces to be used as a tlog for minio
2018-10-02 11:11:12,782 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:382 - INFO - create the zero-os vm on which we will create the minio container
2018-10-02 11:11:16,997 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:440 - INFO - number of possible nodes to use for namespace deployments 23
2018-10-02 11:11:16,997 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:445 - INFO - try to install namespace f664188d-1075-462b-b428-406e23b4b895_tlog on node ac1f6b457b3c
2018-10-02 11:11:22,826 - /opt/code/github/threefoldtech/0-templates/templates/s3/s3.py:376 - INFO - tlog namespaces deployed
2018-10-02 11:13:20,041 - /opt/code/github/threefoldtech/0-robot/zerorobot/template/base.py:214 - ERROR - error executing action install:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socket3.py", line 335, in connect
    raise error(err, strerror(err))
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f3a29c0b8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='capacity.threefoldtoken.com', port=443): Max retries exceeded with url: /api/nodes?farmer=tlre (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f3a29c0b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 185, in install
    raise ns_data_gl.exception
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 165, in deploy_data_namespaces
    namespaces = self._deploy_minio_backend_namespaces()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 334, in _deploy_minio_backend_namespaces
    nodes=self._nodes,
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 45, in _nodes
    nodes = list_farm_nodes(self.data['farmerIyoOrg'])
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 480, in list_farm_nodes
    resp = capacity.api.ListCapacity(query_params={'farmer': farm_organization})[1]
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/api_service.py", line 140, in ListCapacity
    resp = self.client.get(uri, None, headers, query_params, content_type)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 71, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 53, in _handle_data
    res = method(uri, headers=headers, params=params)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='capacity.threefoldtoken.com', port=443): Max retries exceeded with url: /api/nodes?farmer=tlre (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f3a29c0b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Env**
dev
farm: tlre

**Comment by zaibon** [comment]
Not a template issue, reported the issue to the correct repo: https://github.com/threefoldtech/jumpscale_lib/issues/170
