### ISSUE TITLE
s3: error during installation if no nodes found to deploy capacity

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#139]
```
[Tue02 14:45] - base.py           :214 :service-e9b37f29-17d7-4e00-b85d-467c8f722bd0 - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 187, in install
    raise ns_data_gl.exception
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 164, in deploy_data_namespaces
    namespaces = self._deploy_minio_backend_namespaces()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 336, in _deploy_minio_backend_namespaces
    logger=self.logger):
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 445, in deploy_namespaces
    node = nodes[i % len(nodes)]
ZeroDivisionError: integer division or modulo by zero
```

**Comment by serboctor** [comment]
https://github.com/threefoldtech/0-templates/commit/bebdbbbe966891002adbd7faa185c0cfd4ad8d94

**Comment by Pishoy** [comment]
@zaibon please confirm verification steps that should be as follow:

1- choose a farm that all nodes are off 
2- deploy an s3 on that farm by s3 0-templates 
3- i should get a proper error about no nodes are available

**Comment by zaibon** [comment]
@Pishoy that should do it yeah

**Comment by Pishoy** [comment]
verified 
```
In [5]: zt = robot.services.create('github.com/threefoldtech/0-templates/zerotier_client/0.0.1', 'main', args)

In [6]: data = {
   ...:     'farmerIyoOrg': 'bishoy_farm',
   ...:     'mgmtNic': {'id':'1c33c1ced064fefe', 'ztClient': 'main'},
   ...:     'storageType': 'hdd',
   ...:     'storageSize': 50000,
   ...:     'minioLogin': 'admin',
   ...:     'minioPassword': 'adminadmin',
   ...: }
In [8]: s3 = robot.services.create('github.com/threefoldtech/0-templates/s3/0.0.1','s3test', data)

In [9]: s3.schedule_action('install').wait(die=True)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/bin/js_shell in <module>()
----> 1 s3.schedule_action('install').wait(die=True)

/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise RuntimeError(self.eco.message)
    132 
    133         return self

RuntimeError: could not deploy enough namespaces for minio data backend
```
- 0-robot logs 
```
[Thu11 09:37] - s3.py             :451 :service-d5a6a2bd-1ead-4ed4-8103-1a516324fe08 - INFO     - number of possible nodes to use for namespace deployments 0
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 164, in deploy_data_namespaces
    namespaces = self._deploy_minio_backend_namespaces()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 347, in _deploy_minio_backend_namespaces
    raise RuntimeError("could not deploy enough namespaces for minio data backend")
RuntimeError: could not deploy enough namespaces for minio data backend
2018-10-11T09:37:21Z <Greenlet "Greenlet-0" at 0x7f52b2e75148: deploy_data_namespaces> failed with RuntimeError

```
- 0-templates version 
```
root@e7605ba47d5c:/opt/code/github/threefoldtech/0-templates# git log -1
commit b4efeead7bb1cc6d1c5033dc1fb67137e8c395b4
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Oct 10 17:19:03 2018 +0200

    Allow configuring the master tlog in minio (#157)
    
    * Allow configuring the master tlog in minio
    * Extend the minio docs
```
