### ISSUE TITLE
Can't create container with 0-templates container 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/0-templates#167]
# Steps 
```
container_data = {                                                                                        
    ...:     'flist': 'https://hub.grid.tf/tf-bootable/ubuntu:16.04.flist',
    ...:     'mounts': [],
    ...:     'nics': [{'type': 'default','name':"test"}]                                                           
    ...: }
```
```
container = robot.services.create('github.com/threefoldtech/0-templates/container/0.0.1', 'zerodddbcontain
    ...: ere0', data=container_data)            
```
```
container.schedule_action("install").wait(die=True)    
```
# Error
```
'Traceback (most recent call last):\n  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute\n    self._result = self._func()\n  File "/opt/code/github/threefoldtech/0-templates/templates/container/container.py", line 37, in install\n    ports = j.sal_zos.utils.format_ports(self.data[\'ports\'])\nAttributeError: \'SALZos\' object has no attribute \'utils\'\n'

```

**Comment by siddiquagig** [comment]
Duplicate of #https://github.com/threefoldtech/jumpscale_lib/issues/194

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/0-templates/commit/b74784ec4e0fe999316cb4147acd361ca5cfbb54

**Comment by abdulgig** [comment]
Closing this, same as [https://github.com/threefoldtech/jumpscale_lib/issues/194](url)
