### ISSUE TITLE
fail to start new container with zerotier nic once coredns service is running

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#173]
So I was deploying a web gateway (etcd,coredns,traefik) and hit this issue. It seems that once coredns is running, we cannot create any new container that have a zerotier nic.  From the stack trace I see that the robot is trying to authorize the container in the zerotier network, but fail cause it cannot resolve `my.zerotier.com`

```
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/abstracts.py", line 344, in container
    self._container = self.node.containers.get(self._container_name)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/container/Container.py", line 32, in get
    raise LookupError("Could not find container with name {}".format(name))
LookupError: Could not find container with name traefik_traefik_demo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socketcommon.py", line 208, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.5/dist-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "/usr/local/lib/python3.5/dist-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fc20fcf9b00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='my.zerotier.com', port=443): Max retries exceeded with url: /api/network/8850338390ef9f69 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc20fcf9b00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/traefik/traefik.py", line 63, in install
    traefik_sal.deploy()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/traefik/Traefik.py", line 61, in deploy
    self.container
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/abstracts.py", line 346, in container
    self._container = self.node.containers.create(**self._container_data)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/traefik/Traefik.py", line 43, in _container_data
    self.authorize_zt_nics()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/abstracts.py", line 362, in authorize_zt_nics
    authorize_zerotiers(zt_public, self.nics)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/utils.py", line 8, in authorize_zerotiers
    nic.authorize(identify)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/abstracts.py", line 171, in authorize
    network = self.client.network_get(self.networkid)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/zerotier/ZerotierClient.py", line 343, in network_get
    resp = self.client.network.getNetwork(id=network_id)
  File "/usr/local/lib/python3.5/dist-packages/zerotier/network_service.py", line 58, in getNetwork
    return self.client.get(uri, None, headers, query_params, content_type)
  File "/usr/local/lib/python3.5/dist-packages/zerotier/client.py", line 70, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/usr/local/lib/python3.5/dist-packages/zerotier/client.py", line 52, in _handle_data
    res = method(uri, headers=headers, params=params)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='my.zerotier.com', port=443): Max retries exceeded with url: /api/network/8850338390ef9f69 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc20fcf9b00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by delandtj** [comment]
what does `/etc/nsswitch.conf` look like ? (in the robot container)

**Comment by zaibon** [comment]
```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by zaibon** [comment]
ok so we found the problem, look at the resolv.conf of the node robot container:
```
# DNS unset during autobuild of 0-robot

nameserver 172.18.0.1
```
It indeed listen to the zero-os node itself. So when we install coredns and port forward the port 53, the node robot then use coredns as nameserver.

@muhamadazmy What do you think we should do ?

**Comment by muhamadazmy** [comment]
I was affraid that this will happen, hence i raised a flag before that Bola either do port forwarding on a certain nic or make sure that the coredns can resolve all addresses ( to work as proxy dns like dnsmasq does) and take the zos host resolve.conf into account

**Comment by BolaNasr** [comment]
we changed the way or dns resolving so that all containers don't use coredns for querying
so the containers issue should be solved too

**0-template**
https://github.com/threefoldtech/0-templates/commit/9ddeeeca500f893ee0e582d2fb6bde12bff30878
https://github.com/threefoldtech/0-templates/commit/02b09f8f627aefc4bbd1bdf2cefe4bdfaff26aac

**Jumpscale_lib**
https://github.com/threefoldtech/jumpscale_lib/commit/b534479bc8f8fa78f83834d028d3f40bbbd7c08f
https://github.com/threefoldtech/jumpscale_lib/commit/e2350b634cf30dad6fdfdf854f68d16c4f192172

**Comment by BolaNasr** [comment]
we changed the way or dns resolving so that all containers don't use coredns for querying
so the containers issue should be solved too

**0-template**
https://github.com/threefoldtech/0-templates/commit/9ddeeeca500f893ee0e582d2fb6bde12bff30878
https://github.com/threefoldtech/0-templates/commit/02b09f8f627aefc4bbd1bdf2cefe4bdfaff26aac

**Jumpscale_lib**
https://github.com/threefoldtech/jumpscale_lib/commit/b534479bc8f8fa78f83834d028d3f40bbbd7c08f
https://github.com/threefoldtech/jumpscale_lib/commit/e2350b634cf30dad6fdfdf854f68d16c4f192172
