### ISSUE TITLE
VM: issue in monitor action

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#180]
```
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/vm/vm.py", line 64, in _monitor
    vm_sal.deploy()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/vm/ZOS_VM.py", line 553, in deploy
    self.start()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/vm/ZOS_VM.py", line 427, in start
    share_cache=share_cache_enabled(self._flist))
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/zero_os_protocol/KvmManager.py", line 230, in create
    return self._client.json('kvm.create', args, tags=tags)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/zero_os_protocol/BaseClient.py", line 125, in json
    result = self.sync(command, arguments, tags=tags, id=id)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/zero_os_protocol/BaseClient.py", line 115, in sync
    raise ResultError(msg='%s' % result.data, code=result.code)
JumpscaleLib.clients.zero_os_protocol.Response.ResultError: "port already in use"
```

**Comment by zaibon** [comment]
So it seems this bug is cause by the logic behind port forwarding in the vm template.
Specifically this function:
https://github.com/threefoldtech/0-templates/blob/9ddeeeca500f893ee0e582d2fb6bde12bff30878/templates/vm/vm.py#L230-L245
We see that it only ask zero-os for port to use if there is not source provided in the list of port forward. But this function is called like this : https://github.com/threefoldtech/0-templates/blob/9ddeeeca500f893ee0e582d2fb6bde12bff30878/templates/vm/vm.py#L30-L32

Which mean we save the ports in the service data the first time, then all the next call will never ask zero-os for which port to use. We need to change this logic to always ask zero-os for free port when starting the VM. So we make sure that we don't have conflicts in port forward

**Comment by zaibon** [comment]
In order to solve the problem of conflicting port forwards one and for all we could introduce a port manager template that will be responsible of giving out free port for any service deployed on a node. This template will then be the only source of truth about reserved port for a node.

I've tried to formalized a bit the API of such a port manager:

## Schema:
```capnp
struct Schema {
    ports @0 :List(Port);

    struct Port {
        port @0 :Integer;
        service_guid @1 :Text;
    }
}
```


## API:

```python
def __init__(self):
    def f():
        while True():
            yield self.node_sal.freeports(1)
    self.port_iter = f()

def reserve(self, service_guid, n=1):
    used_ports = [x['port'] for x in self.data['ports']]
    selected_ports = []
    
    for _ in range(n):
        port = self._reserve(excluse=used_ports)
        used_ports.append(port)
        selected_ports.append(port)
        self.ports.append({'port':port, 'service_guid': service_guid})
    
    return selected_ports

def release(self, service_guid, ports):
    for item in list(self.data['ports']):
        if item['port'] in ports:
            if item['service_guid'] != service_guid:
                raise # only the service that reserve the part can release it
            self.data['ports'].remove(item)



def _reserve(self, exclude):
    port = next(self.port_iter)
    while port in exclude:
        # this will eventually raised if no port is found
        port = next(self.port_iter)

    #  if we reached here, we found a free port
    return port
```
