### ISSUE TITLE
improper logs comes from robot when create an ETCD template 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/0-templates#191]
- improper logs comes from robot when create an ETCD template  when create an ETCD with undefined zerotier client 

- try to give args with undefined zerotier client then create ETCD service 
- i expect logs inform me that the zerotier client does not exist instead `Could not deploy enough etcds for cluster`

```

In [46]: args = {
    ...:    ...:     'nics': [{'name': 'ten', 'type': 'zerotier', 'ztClient':'undefined', 'id': '35c192ce9b7015e9'}],
    ...:    ...:     'farmerIyoOrg': 'kristof-farm',
    ...:    ...:     'nrEtcds': 3
    ...:    ...:     }  
    ...:     

In [47]: etcd = robot.services.create('github.com/threefoldtech/0-templates/etcd_cluster/0.0.1', 'etcdtest', data=args)

In [48]: s3.schedule_action('install').wait(die=True)
Out[48]: install


In [50]: etcd.schedule_action('install').wait(die=True)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/bin/js_shell in <module>()
----> 1 etcd.schedule_action('install').wait(die=True)

/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise RuntimeError(self.eco.message)
    132 
    133         return self

RuntimeError: Could not deploy enough etcds for cluster
```
- 0-robot logs 
```[Thu01 11:38] - pywsgi.py         :1182:j.zerorobot          - INFO     - ::ffff:127.0.0.1 - - [2018-11-01 11:38:44] "GET /services/484cdfaf-f19f-4bb7-8c64-9ee9315f175e/task_list/06856fad-30d9-41d2-8c90-d43c2c5c30e9 HTTP/1.1" 200 372 0.019438
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 22
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b27243c
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 21
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b2723e0
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 20
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b457338
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 19
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b456cf4
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 18
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b4571d0
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 17
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b4571cc
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 16
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b4571c8
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 15
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b4571d8
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 14
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b457344
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 13
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b4573d4
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 12
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b272400
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 11
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b272370
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 10
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b456b98
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 9
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b27224c
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 8
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b272328
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 7
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b2722e8
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 6
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b4575a8
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 5
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b457630
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 4
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b272268
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 3
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b457488
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 2
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b272260
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 1
[Thu01 11:38] - etcd_cluster.py   :123 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - try to install etcd on node ac1f6b2723a0
[Thu01 11:38] - etcd_cluster.py   :119 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - INFO     - number of possible nodes to use for namespace deployments 0
[Thu01 11:38] - base.py           :214 :service-484cdfaf-f19f-4bb7-8c64-9ee9315f175e - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/etcd_cluster/etcd_cluster.py", line 188, in install
    etcds = self._deploy_etcd_cluster()
  File "/opt/code/github/threefoldtech/0-templates/templates/etcd_cluster/etcd_cluster.py", line 109, in _deploy_etcd_cluster
    raise RuntimeError('Could not deploy enough etcds for cluster')
RuntimeError: Could not deploy enough etcds for cluster
```
- 0-templates version 
```
commit 4c752681b84a8edfe9aeca09a8f7471a47f9b5e5
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Oct 31 13:11:55 2018 +0200

    Fix state check in etcd
```

**Comment by Pishoy** [comment]
- also we need to remove actions stop and start from readme as those actions are not working 
```

In [56]: etcd.schedule_action('stop').wait(die=True)
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
```
