### ISSUE TITLE
zrobot_config service crashes the robot

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-templates#199]
After setting the `zrobot_config` serviceto setup the configmanager with zdb backend, the robot crashes on restart to take the new zdb configmanager backend.
Similar error to https://github.com/threefoldtech/jumpscale_core/issues/144
```
In [31]: res = cc.client.subscribe("zrobot")

In [32]: res.stream()
[Tue06 13:49] - .startup.py       :47  :j.zrobot_statup      - INFO     - farmer_id expired, trying to refresh
[Tue06 13:49] - DbConfigManager.py:104 :anager.dbconfigmanager - WARNING  - using default namespace.
[Tue06 13:49] - DbConfigManager.py:104 :anager.dbconfigmanager - WARNING  - using default namespace.
[Tue06 13:49] - DbConfigManager.py:104 :anager.dbconfigmanager - WARNING  - using default namespace.
[Tue06 13:49] - DbConfigManager.py:104 :anager.dbconfigmanager - WARNING  - using default namespace.
[Tue06 13:49] - .startup.py       :52  :j.zrobot_statup      - ERROR    - fail to refresh farmer_id.                 To fix this, generate a new farmer id, update your kernel with it and reboot the machine
Traceback (most recent call last):
  File "/.startup.py", line 45, in get_admin_organization
    claims = jwt.decode(token, iyo_pub_key)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 153, in decode
    options=defaults)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 461, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 302, in _validate_exp
    raise ExpiredSignatureError('Signature has expired.')
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

    return NACL(name, secret, sshkeyname=j.tools.configmanager.keyname)
  File "/usr/lib/python3/dist-packages/jumpscale.py", line 851, in configmanager
    self._configmanager = ConfigFactory()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 48, in __init__
    self._impl = DbConfigManager()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 45, in __init__
    self.set_namespace(self._namespace)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 126, in set_namespace
    self.configure_keys(self._zdbsimplecl.namespace.get('key.priv'), self._zdbsimplecl.namespace.get('key.pub'), self._zdbsimplecl.namespace.get('key.seed'), self._zdbsimplecl.namespace.get('key.seed'))
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 67, in configure_keys
    self.prepare_mgmt_repo()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 182, in prepare_mgmt_repo
    nacl = j.data.nacl.get("key")
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/data/nacl/NACLFactory.py", line 25, in get
    return NACL(name, secret, sshkeyname=j.tools.configmanager.keyname)
  File "/usr/lib/python3/dist-packages/jumpscale.py", line 851, in configmanager
    self._configmanager = ConfigFactory()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 48, in __init__
    self._impl = DbConfigManager()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 45, in __init__
    self.set_namespace(self._namespace)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 121, in set_namespace
    self._zdbsimplecl.namespace_new(namespace, die=False)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/zdb/ZDBClient.py", line 81, in namespace_new
    if self.namespace_exists(name):
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/zdb/ZDBClient.py", line 56, in namespace_exists
    raise RuntimeError("could not check namespace:%s, error:%s" % (name, e))
RuntimeError: could not check namespace:default, error:maximum recursion depth exceeded while calling a Python object
Out[32]: 81

```

**Comment by chrisvdg** [comment]
@zaibon worked on some fixes and I don't get the above error any, the robot now crashes with 
```sh
In [19]: res.stream()
[Thu08 10:06] - .startup.py       :47  :j.zrobot_statup      - INFO     - farmer_id expired, trying to refresh
[Thu08 10:06] - DbConfigManager.py:104 :anager.dbconfigmanager - INFO     - using namespace MAN-DC01-G1025-ARC07
[Thu08 10:06] - .startup.py       :52  :j.zrobot_statup      - ERROR    - fail to refresh farmer_id.                 To fix this, generate a new farmer id, update your kernel with it and reboot the machine
Traceback (most recent call last):
  File "/.startup.py", line 45, in get_admin_organization
    claims = jwt.decode(token, iyo_pub_key)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 153, in decode
    options=defaults)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 461, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 302, in _validate_exp
    raise ExpiredSignatureError('Signature has expired.')
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.startup.py", line 167, in <module>
    main()
  File "/.startup.py", line 163, in main
    start_robot()
  File "/.startup.py", line 138, in start_robot
    admin_org = get_admin_organization(kernel_args)
  File "/.startup.py", line 49, in get_admin_organization
    token = j.clients.itsyouonline.refresh_jwt_token(token)
  File "/usr/lib/python3/dist-packages/jumpscale.py", line 969, in itsyouonline
    from JumpscaleLib.clients.itsyouonline.IYOFactory import IYOFactory as IYOFactory
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/itsyouonline/IYOFactory.py", line 4, in <module>
    from .IYOClient import IYOClient
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/itsyouonline/IYOClient.py", line 17, in <module>
    JSConfigBase = j.tools.configmanager.base_class_config
  File "/usr/lib/python3/dist-packages/jumpscale.py", line 1930, in configmanager
    self._configmanager = ConfigFactory()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 48, in __init__
    self._impl = DbConfigManager()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 45, in __init__
    self.set_namespace(self._namespace)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 119, in set_namespace
    self._zdbsimplecl.namespace_new(namespace, die=False)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/zdb/ZDBClient.py", line 83, in namespace_new
    return self.namespace_get(name)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/zdb/ZDBClient.py", line 60, in namespace_get
    self.namespaces[name] = ZDBClientNS(self, name)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/zdb/ZDBClientNS.py", line 46, in __init__
    self.redis.execute_command("SELECT ", self.nsname)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: Namespace not found
Out[19]: 5
```

zdb client doesn't return any namespaces (not even `default`)
```
In [20]: zdb = j.clients.zdb.configure(instance="test", addr="tlre.gig.tech", port="9900")

In [21]: zdb.namespaces
Out[21]: {}

```

**Comment by xmonader** [comment]
```bash
In [7]: cl.namespaces
Out[7]: {'default': <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS at 0x7f13843b79b0>}

In [8]: cl.namespace_new("anewnamespace")
Out[8]: <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS at 0x7f13840a39e8>

In [9]: cl.namespaces
Out[9]: 
{'anewnamespace': <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS at 0x7f13840a39e8>,
 'default': <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS at 0x7f13843b79b0>}

In [10]: cl = j.clients.zdbsimple.get()

In [11]: cl.namespaces
Out[11]: {}

In [12]: ans = cl.namespace_get("anewnamespace")
NAMESPACES NOW:  {'anewnamespace': <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS object at 0x7f13840ae390>}

In [13]: ans
Out[13]: <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS at 0x7f13840ae390>

In [14]: ans.list()
Out[14]: []



In [17]: zdbcl = j.clients.zdb.get('main', {})
NAMESPACES NOW:  {'default': <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS object at 0x7f137e44f5f8>}
NAMESPACES NOW:  {'default': <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS object at 0x7f137e44f5f8>}

In [18]: zdbcl
Out[18]: redis:main           127.0.0.1                :9900

In [19]: zdbcl.zdb.namespaces
Out[19]: {}

In [20]: zdbcl.zdb.namespace_get("anewnamespace")

Out[20]: <Jumpscale.clients.zdb.ZDBClientNS.ZDBClientNS at 0x7f137e41d7f0>

In [21]: ns = _

In [22]: ns.list()
Out[22]: []


In [25]: ns.redis.execute_command("NSLIST")
Out[25]: [b'default', b'anamespace', b'anamespace2', b'anewnamespace']


```

namespaces property is only about the created namespaces in the context of zdb client (misleading)

**Comment by chrisvdg** [comment]
@xmonader, alright, we still need to figure out why the zdb namespace for the robot is there in the backend but not reachable

**Comment by chrisvdg** [comment]
Gave it another namespace that didn't contain capital letters nor dashes (`-`)  and it works now, is there any docs on illegal chars for zdb namespaces?

Also noticed that if you create a namespaces with all small caps and then create one with the same name in uppercase. it will use the lowercase namespace for both

**Comment by chrisvdg** [comment]
This might be an issue with the client, will investigate further and report in the corresponding repo if reproducible.
