### ISSUE TITLE
Fishy error while installing s3 on bancadati

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/0-templates#242]
```
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 639, in _install_namespace
    raise NamespaceDeployError(task.eco.message, node)
s3.NamespaceDeployError: (NamespaceDeployError(...), '3 services found')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 643, in _install_namespace
    raise NamespaceDeployError(str(err), node)
s3.NamespaceDeployError: (NamespaceDeployError(...), "(NamespaceDeployError(...), '3 services found')")
2018-11-27T10:25:10Z <Greenlet "Greenlet-0" at 0x7f29b2642648: <bound method S3._install_namespace of <s3.S3 object at 0x7f29d6629da0>>(node={'farmer_id': 'bancadati.threefold.grid.farm01', ', name='03856c5f', disk_type='hdd', size=2, password='txk0tfin7d7ybcww4syu34azd1cst4ie')> failed with NamespaceDeployError
```

**Comment by serboctor** [comment]
It seems that there were multiple node_port_manager services on most of bancadati nodes. I ran a script to clean it up and @zaibon is looking into the cause of this in zrobot.

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/0-templates/commit/d326da18d1316c43637be18d94092d2e72a380c3
