### ISSUE TITLE
explorer template upgrade fails

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-templates#29]
```
In [6]: robot.templates.checkout_repo('https://github.com/threefoldtoken/0-templ
   ...: ates')

UnhandledAPIErrorTraceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 robot.templates.checkout_repo('https://github.com/threefoldtoken/0-templates')

/opt/code/github/zero-os/0-robot/zerorobot/dsl/ZeroRobotManager.py in checkout_repo(self, url, revision)
    204         }
    205         try:
--> 206             self._client.api.templates.CheckoutVersionTemplateRepo(data)
    207         except HTTPError as err:
    208             e = err.response.json()

/opt/code/github/zero-os/0-robot/JumpScale9Zrobot/clients/zerorobot/client/templates_service.py in CheckoutVersionTemplateRepo(self, data, headers, query_params, content_type)
     76             raise UnmarshallError(resp, msg)
     77         except UnhandledAPIError as uae:
---> 78             raise uae
     79         except Exception as e:
     80             raise UnmarshallError(resp, e.message)

/opt/code/github/zero-os/0-robot/JumpScale9Zrobot/clients/zerorobot/client/templates_service.py in CheckoutVersionTemplateRepo(self, data, headers, query_params, content_type)
     72             message = 'unknown status code={}'.format(resp.status_code)
     73             raise UnhandledAPIError(response=resp, code=resp.status_code,
---> 74                                     message=message)
     75         except ValueError as msg:
     76             raise UnmarshallError(resp, msg)

UnhandledAPIError: 
```

```
In [8]: con.subscribe('zrobot')
[Wed09 10:25] - Client.py         :229 :ts.zero_os.bootstrap-1 - DEBUG    - 087a8809-6de9-4203-95f2-bdc707a49df8 >> g8core.corex.dispatch(command={'max_time': None, 'command': 'core.subscribe', 'id': None, 'queue': None, 'arguments': {'id': 'zrobot'}, 'tags': None, 'stream': True}, container=1)
Out[8]: <JumpScale9Lib.clients.zero_os.Response.Response at 0x7fbadb989e48>

In [9]: _.stream()

[Wed09 10:25] - template_collection.py:120 :j.zerorobot          - INFO     - checkout master for repo https://github.com/threefoldtoken/0-templates
[Wed09 10:25] - template_collection.py:135 :j.zerorobot          - INFO     - reload templates
[Wed09 10:25] - template_collection.py:139 :j.zerorobot          - INFO     - upgrading <explorer.Explorer object at 0x7f1476e4cd30>
[Wed09 10:25] - service_collection.py:100 :j.zerorobot          - INFO     - upgrade service explorer (0074ae04-58a1-45fd-a2da-1a28bf00b174) to github.com/threefoldtoken/0-templates/explorer/0.0.1
[Wed09 10:25] - pywsgi.py         :1146:j.zerorobot          - INFO     - ::ffff:172.18.0.1 - - [2018-05-09 10:25:54] "PUT /templates HTTP/1.1" 204 115 12.072101
[Wed09 10:25] - base.py           :201 :service-0074ae04-58a1-45fd-a2da-1a28bf00b174 - ERROR    - error executing action _monitor:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/threefoldtoken/0-templates/templates/explorer/explorer.py", line 198, in _monitor
    if self._explorer_sal.explorer.is_running():
AttributeError: 'TfChainExplorer' object has no attribute 'explorer'
```

**Comment by LeeSmet** [comment]
It seems that the new mount point is not added if a container is upgraded after this

**Comment by zaibon** [comment]
@LeeSmet can you validate that your client code for the robot you use is the same as 
https://github.com/zero-os/0-robot/blob/master/JumpScale9Zrobot/clients/zerorobot/client/templates_service.py#L66

**Comment by LeeSmet** [comment]
```
def CheckoutVersionTemplateRepo(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        Checkout a certain branch/tag/revision of a template repository
        It is method for PUT /templates
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/templates"
        resp = self.client.put(uri, data, headers, query_params, content_type)
        try:

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)
```

**Comment by zaibon** [comment]
yep so that's what I though, small but in the client code you use. It expects a response from this call, while the server doesn't return any body in the response, thus the error you have.
Released version of 0robot doesn't have this code.

This explain your bug client side.

For the error server side, it is a bug in the template that is solved at: https://github.com/threefoldtoken/0-templates/tree/explorer_monitor

**Comment by zaibon** [comment]
Don't know what happens but the fix dosen't seems to be present anymore...
And 
> For the error server side, it is a bug in the template that is solved at: https://github.com/threefoldtoken/0-templates/tree/explorer_monitor

point to something not related at al with the fix...

**Comment by zaibon** [comment]
https://github.com/threefoldtoken/0-templates/commit/15d81bdaf113c4f7b583b70e28023b3f98366c56
