### ISSUE TITLE
Cleaning up a namespace reservation raises an error

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/0-templates#313]
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/grid_broker/templates/reservation/reservation.py", line 337, in _cleanup
    self.state.check('actions', 'cleanup', 'ok')
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/template/state.py", line 86, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:cleanup:ok failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 81, in execute
    self._result = self._execute_greenlet.get(block=True, timeout=None)
  File "src/gevent/greenlet.py", line 709, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.5/dist-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/grid_broker/templates/reservation/reservation.py", line 343, in _cleanup
    self._cleanup_service(created_service['robot'], created_service['id'])
  File "/opt/code/github/threefoldtech/grid_broker/templates/reservation/reservation.py", line 359, in _cleanup_service
    service.schedule_action('uninstall').wait(die=True)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 141, in wait
    raise RuntimeError(self.eco.message)
RuntimeError: delete() takes from 2 to 3 positional arguments but 4 were given

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/0-templates/commit/e48da8183514a1ec92e468073ae767682192d610
