### ISSUE TITLE
create vm without required parameter return internal server error

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#55]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/140](), opened by @Dinaamagdy*

- create vm without providing flist return internal server error 
## Blueprint
```
services:

  - github.com/zero-os/0-templates/vm/0.0.1__45ae5ba2:

actions:
  - template: github.com/zero-os/0-templates/vm/0.0.1
    actions: ['install']

```

## Error from client 
```
ipdb> 
HTTPError('500 Server Error: INTERNAL SERVER ERROR for url: http://147.75.32.61:6600/blueprints',)
ipdb> err.response.json()
{'msg': 'unexpected error', 'code': 500}
ipdb> 

```
## Error from server 
```
ed06 12:02] - pywsgi.py         :1170:j.zerorobot          - INFO     - ::ffff:147.75.101.31 - - [2018-06-06 12:02:54] "POST /blueprints HTTP/1.1" 500 165 0.016835
[Wed06 12:02] - vm.py             :36  :service-f23939f1-c61d-423f-8d25-ce6e24032b18 - INFO     - Monitor vm cd6438a2
[Wed06 12:02] - base.py           :204 :service-f23939f1-c61d-423f-8d25-ce6e24032b18 - ERROR    - error executing action _monitor:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category actions does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 37, in _monitor
    self.state.check('actions', 'install', 'ok')
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:install:ok failed

[Wed06 12:03] - node.py           :46  :service-2e8d94dc-25ce-4f44-8f38-dac400140abf - INFO     - Monitoring node local
[Wed06 12:03] - node.py           :92  :service-2e8d94dc-25ce-4f44-8f38-dac400140abf - INFO     - storage pool ac1f6b2d3598_fscache doesn't exist on node ac1f6b2d3598
[Wed06 12:03] - vm.py             :36  :service-f23939f1-c61d-423f-8d25-ce6e24032b18 - INFO     - Monitor vm cd6438a2
[Wed06 12:03] - base.py           :204 :service-f23939f1-c61d-423f-8d25-ce6e24032b18 - ERROR    - error executing action _monitor:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category actions does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 37, in _monitor
    self.state.check('actions', 'install', 'ok')
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:install:ok failed

```

**Comment by rkhamis** [comment]
*commented by @Dinaamagdy
another problem 
when the error code is 500 the key of json dict be 'msg' 
{'msg': 'unexpected error', 'code': 500}
but when the error code 401 of json dict be 'message'
*

**Comment by rkhamis** [comment]
*commented by @zaibon
should be fixed by https://github.com/zero-os/0-robot/commit/06291484c4dc98756ddf35a93a5d413047df26d9*

**Comment by hossnys** [comment]
verified :
js branch : development [f182ac3](https://github.com/threefoldtech/jumpscale_core/commit/f182ac37b4a284361615fb5372389967b82af1fa)
0-templates: development [6586c03](https://github.com/threefoldtech/0-templates/commit/6586c0327877f926c74f41e9fbcf1c1587717698)
zos-node : development 6a07840

but it needs some improvements in specifying the error type that robot give back which will be handled in issue https://github.com/threefoldtech/0-robot/issues/37
