### ISSUE TITLE
Failed to deploy a VM with a data disk attached

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#56]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/139](), opened by @ahussein*

I have a script that is trying to deploy a couple of VMs on top of ZOS node. For this I am using the ZeroRobot python client to communicate with the node robot of my zos node.
When I try to deploy the vm i get the following error:
```
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 59, in install
    vm_sal.deploy()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 490, in deploy
    self.update_nics(realityinfo)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 523, in update_nics
    self.node.client.kvm.add_nic(self.uuid, nic.type, nic.networkid, nic.hwaddr)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/KvmManager.py", line 400, in add_nic
    return self._client.json('kvm.add_nic', args)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/ContainerManager.py", line 126, in json
    result = self.sync(command, arguments, tags=tags, id=id)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/ContainerManager.py", line 116, in sync
    raise ResultError(msg='%s' % result.data, code=result.code)
JumpScale9Lib.clients.zero_os.Response.ResultError: "failed to attach device: virError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'device_add': PCI: slot 6 function 0 not availab
t-pci, in use by virtio-blk-pci')"
"failed to attach device: virError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'device_add': PCI: slot 6 function 0 not available for virtio-net-pci, in use by virtio-blk-pci')"
```
**Environment Details**
Host: packet.net
ZOS version: development

**Script details***
The script is trying to execute the following code:
```python
    sshkey = j.clients.sshkey.get(sshkeyname)
    zrobot_cl = j.clients.zrobot.robots[zos_node_name]
    tft_node_data = {
    'name': 'tft_node',
    'flist': 'https://hub.gig.tech/abdelrahman_hussein_1/ubuntucryptoexchange.flist',
    'memory': 1024 * 8,
    'cpu': 2,
    'nics':[{'type': 'default', 'name': 'nic01'}],
    'ports':[{'name': 'ssh', 'source': 2250, 'target':22}],
    'configs': [{'path': '/root/.ssh/authorized_keys', 'content': sshkey.pubkey,
                 'name': 'sshauthorizedkeys'}],
    }
    data_disk = {'size': 100, 'mountPoint': '/mnt/data', 'diskType': 'ssd', 'filesystem': 'btrfs', 'name': 'data'}
 
    disk_srv = zrobot_cl.services.find_or_create('github.com/zero-os/0-templates/vdisk/0.0.1', 'tft_data_disk', data_disk)
    disk_srv.schedule_action('install').wait(die=True)
    disk_url = url = disk_srv.schedule_action('private_url').wait(die=True).result
    data_disk['url'] = disk_url

    tft_node_data['disks'] = [data_disk]

 
    tft_node_srv = zrobot_cl.services.find_or_create('github.com/zero-os/0-templates/vm/0.0.1', tft_node_data['name'], tft_node_data)
    task = tft_node_srv.schedule_action('install')
````

**Comment by rkhamis** [comment]
*commented by @zaibon
What version of 0-OS are you using?*

**Comment by rkhamis** [comment]
*commented by @ahussein
IPXE url is used for booting the ZOS node and it uses latest from development branch*

**Comment by hossnys** [comment]
verified :
js branch : development [f182ac3](https://github.com/threefoldtech/jumpscale_core/commit/f182ac37b4a284361615fb5372389967b82af1fa)
0-templates: development [6586c03](https://github.com/threefoldtech/0-templates/commit/6586c0327877f926c74f41e9fbcf1c1587717698)
zos-node : development 6a07840
