### ISSUE TITLE
Can't use zerotier nic in VM template

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#60]
*Issue migrated from [https://api.github.com/repos/zero-os/0-templates/issues/116](), opened by @zaibon*

```
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 39, in _monitor
    if self._vm_sal.is_running():
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 26, in _vm_sal
    return self._node_sal.primitives.from_dict('vm', data)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/primitives.py", line 151, in from_dict
    vm.from_dict(data)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 447, in from_dict
    nicobj = self.nics.add(nic['name'], nic['type'], nic.get('id'), nic.get('hwaddr'))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 237, in add
    raise RuntimeError('Zerotier can not be added when the VM is running')
RuntimeError: Zerotier can not be added when the VM is running
```

**Comment by rkhamis** [comment]
*commented by @grimpy
Zerotier can only be added when a VM is stopped because we configure it insde the os with the configs option of zero-os which is only applied (and can only working) before the vm is started itself.*

**Comment by hossnys** [comment]
verified :
js branch : development
 zos-node : development
