### ISSUE TITLE
failing in installing the VM will install a VDisk

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#70]
*Issue migrated from [https://api.github.com/repos/Jumpscale/digital_me/issues/41](), opened by @islamTaha12*

**Description**
I tried to create a VM with the wrong ZT, so the installation of the VM failed but the VDisk was created

**Steps**
```python
In [117]: data = {
     ...:  'nodeId': 'ac1f6b2d34b0',
     ...:  'disks': [{
     ...:          'diskType': 'ssd',
     ...:          'size': 1,
     ...:          'mountPoint': '/mnt',
     ...:          'filesystem': 'btrfs',
     ...:          'label': 'xtremx'
     ...:      }],
     ...:  'image': 'ubuntu',
     ...:  'memory': 2048,
     ...:  'cpu':4,
     ...:  'zerotier': {'id': '1c33c1ced09cf5fe', 'ztClient': 'newWorker2'},
     ...:  'configs': [{'path': '/root/.ssh/authorized_keys', 'content': mykey, 
     ...: 'name': 'sshkey'}]
     ...:  }
     ...:  

In [118]: 

In [118]: 

In [118]: vmservice = robot.services.create('github.com/jumpscale/digital_me/vm/0.0.1', service_name='vm003', data=data)

In [119]: vmservice.schedule_action('install').wait(die=True)
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 86, in install
    vm_sal.deploy()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 496, in deploy
    self.start()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 383, in start
    authorize_zerotiers(publiczt, self.nics)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/utils.py", line 6, in authorize_zerotiers
    nic.authorize(identify)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/abstracts.py", line 167, in authorize
    network = self.client.network_get(self.networkid)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerotier/ZerotierClient.py", line 309, in network_get
    resp = self.client.network.getNetwork(id=network_id)
  File "/usr/local/lib/python3.5/dist-packages/zerotier/network_service.py", line 58, in getNetwork
    return self.client.get(uri, None, headers, query_params, content_type)
  File "/usr/local/lib/python3.5/dist-packages/zerotier/client.py", line 70, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/usr/local/lib/python3.5/dist-packages/zerotier/client.py", line 57, in _handle_data
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://my.zerotier.com/api/network/1c33c1ced09cf5fe
---------------------------------------------------------------------------
ErrorConditionObject                      Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 vmservice.schedule_action('install').wait(die=True)

/opt/code/github/zero-os/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise self.eco
    132 
    133         return self

ErrorConditionObject: 404 Client Error: Not Found for url: https://my.zerotier.com/api/network/1c33c1ced09cf5fe
```
- Now list the zdb namespaces and the vdisk services in the zod node
![image](https://user-images.githubusercontent.com/17981089/43208139-0267090c-902a-11e8-8b8a-70925461b4f3.png)

as u can see there is `..._xtremx` disk however the vm wasn't created.

**Env**
zos 1.4.1
js9 development

**Comment by rkhamis** [comment]
*commented by @serboctor
A failing install doesn't clean-up created resources/services......uninstalling the vm service will clean-up everything.*
