### ISSUE TITLE
Installing a VM with not enough resources raise an error 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-templates#73]
*Issue migrated from [https://api.github.com/repos/Jumpscale/digital_me/issues/35](), opened by @islamTaha12*

when there are not enough resources, JS will throw an error while I expect that It returns 'not enough resources messages'
```
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 77, in execute
    self._result = self._func(**self._args)
  File "/opt/code/github/zero-os/0-templates/templates/node/node.py", line 219, in create_zdb_namespace
    raise NoNamespaceAvailability(message)
node.NoNamespaceAvailability: Not enough free space for namespace creation with size 20 and type SSD,NVME
ERROR
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vdisk/vdisk.py", line 101, in uninstall
    self._zerodb.schedule_action('namespace_delete', args={'name': self.data['nsName']}).wait(die=True)
  File "/opt/code/github/zero-os/0-templates/templates/vdisk/vdisk.py", line 42, in _zerodb
    return self.api.services.get(template_uid=ZERODB_TEMPLATE_UID, name=self.data['zerodb'])
  File "/opt/code/github/zero-os/0-robot/zerorobot/dsl/ZeroRobotAPI.py", line 75, in get
    raise scol.ServiceNotFoundError("service not found: query was: %s" % str(kwargs))
zerorobot.service_collection.ServiceNotFoundError: "service not found: query was: {'template_uid': 'github.com/zero-os/0-templates/zerodb/0.0.1', 'name': ''}"
ERROR
****
```

Env
zOS: 1.4.1
0-robot: development
0-dm: master
0-template: developmet
js9: dev

**Comment by zaibon** [comment]
once the 3bot will be responsbile for ordering capacity and use pre-reservation we should not have these kind of issue anymore
